version: '3'

services:
  jekyll:
    image: jekyll/jekyll:4.2.0
    command: bash -c "bundle install && bundle exec jekyll serve --livereload"
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=production 